### ISSUE TITLE
Support for community specific categories

### ISSUE THREAD

**Issue by KlutzyBubbles** [GreenTF/upload-thunderstore-package#27]
After raising an issue with tcli [here](https://github.com/thunderstore-io/thunderstore-cli/issues/99). It looks to be an entirely different config option that this action doesnt support.

Perhaps an option like 'category_community' which will make 

```
[publish.categories]
category_community=[categories]
```

instead of

```
[publish]
categories=[categories]
```

I havent actually tried tcli publish with the category community yet (i dont have any updates to publish). But i am confident based off of documentation and the issue that it will work.

**Comment by AnActualEmerald** [comment]
Oh okay, I don't know how I missed that before

Seems weird to me that it would have to be explicit like that but whatever, I'll get a fix put together asap

**Comment by MythicManiac** [comment]
The CLI build supporting this syntax is only a few days old so that'd be why (the API has existed for a while now though).

Categories have always been bound to some individual community, it just hasn't been very obvious before since that community was implicitly derived from the domain that was used when uploading. That used to work fine before we started consolidating all communities under the same domain.

With all of that in mind, the category system really isn't suited well for this, I mean there's a reason they're not in the package metadata (since what categories exist are unique to each community). There's a rough idea on how this should work on a community-agnostic level, which would be something akin to tags which you can add to the package metadata directly. 

Categories are intended as something the community can update later on & use for display purposes, whereas tags would be declared by the package author and remain immutable.
